# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-15 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_en_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='desc',
        ),
        migrations.AddField(
            model_name='menucategory',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop'),
        ),
        migrations.AddField(
            model_name='shopdesc',
            name='shop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop'),
        ),
        migrations.AlterField(
            model_name='shopdesc',
            name='method_of_payment',
            field=models.CharField(blank=True, max_length=50, verbose_name='결제수단'),
        ),
    ]
