# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-25 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdesc',
            name='intro_message',
            field=models.TextField(blank=True, null=True, verbose_name='사장님알림'),
        ),
    ]
